// Every source is documented here but commented out until it's implemented.
// When you implement a new source, add a test to testapp.js.

export {default as BingMaps} from './bingmaps'
//export {default as CartoDB} from './cartodb'
//export {default as Cluster} from './cluster'
//export {default as Image} from './image'
export {default as ImageArcGISRest} from './image-arcgis-rest'
//export {default as ImageCanvas} from './image-canvas'
//export {default as ImageMapGuide} from './image-map-guide'
//export {default as ImageStatic} from './image-static'
//export {default as ImageWMS} from './image-wms'
export {default as OSM} from './osm'
//export {default as Raster} from './raster'
//export {default as Source} from './source'
//export {default as Stamen} from './stamen'
//export {default as TileArcGISRest} from './tile-arcgis-rest'
//export {default as TileDebug} from './tile-debug'
//export {default as TileJSON} from './tile-json'
//export {default as TileWMS} from './tile-wms'
//export {default as TileWMS} from './tile-wms'
//export {default as UTFGrid} from './utf-grid'
//export {default as UrlTile} from './url-tile'
export {default as Vector} from './vector'
//export {default as VectorTile} from './vector-tile'
//export {default as WMTS} from './wmts'
//export {default as XYZ} from './xyz'
//export {default as Zoomify} from './zoomify'
